BEGIN;
INSERT INTO dashboard_slices (dashboard_id, slice_id) VALUES (3, 1) ON CONFLICT DO NOTHING;
INSERT INTO dashboard_slices (dashboard_id, slice_id) VALUES (3, 2) ON CONFLICT DO NOTHING;
INSERT INTO dashboard_slices (dashboard_id, slice_id) VALUES (3, 3) ON CONFLICT DO NOTHING;
INSERT INTO dashboard_slices (dashboard_id, slice_id) VALUES (3, 4) ON CONFLICT DO NOTHING;
INSERT INTO dashboard_slices (dashboard_id, slice_id) VALUES (3, 5) ON CONFLICT DO NOTHING;
INSERT INTO dashboard_slices (dashboard_id, slice_id) VALUES (3, 6) ON CONFLICT DO NOTHING;
INSERT INTO dashboard_slices (dashboard_id, slice_id) VALUES (3, 7) ON CONFLICT DO NOTHING;
INSERT INTO dashboard_slices (dashboard_id, slice_id) VALUES (3, 8) ON CONFLICT DO NOTHING;
INSERT INTO dashboard_slices (dashboard_id, slice_id) VALUES (3, 9) ON CONFLICT DO NOTHING;
INSERT INTO dashboard_slices (dashboard_id, slice_id) VALUES (3, 10) ON CONFLICT DO NOTHING;
INSERT INTO dashboard_slices (dashboard_id, slice_id) VALUES (3, 11) ON CONFLICT DO NOTHING;
INSERT INTO dashboard_slices (dashboard_id, slice_id) VALUES (3, 12) ON CONFLICT DO NOTHING;
INSERT INTO dashboard_slices (dashboard_id, slice_id) VALUES (3, 13) ON CONFLICT DO NOTHING;
INSERT INTO dashboard_slices (dashboard_id, slice_id) VALUES (3, 14) ON CONFLICT DO NOTHING;
INSERT INTO dashboard_slices (dashboard_id, slice_id) VALUES (3, 15) ON CONFLICT DO NOTHING;
INSERT INTO dashboard_slices (dashboard_id, slice_id) VALUES (3, 16) ON CONFLICT DO NOTHING;
INSERT INTO dashboard_slices (dashboard_id, slice_id) VALUES (3, 17) ON CONFLICT DO NOTHING;
INSERT INTO dashboard_slices (dashboard_id, slice_id) VALUES (3, 18) ON CONFLICT DO NOTHING;
INSERT INTO dashboard_slices (dashboard_id, slice_id) VALUES (3, 19) ON CONFLICT DO NOTHING;
INSERT INTO dashboard_slices (dashboard_id, slice_id) VALUES (3, 20) ON CONFLICT DO NOTHING;
INSERT INTO dashboard_slices (dashboard_id, slice_id) VALUES (3, 21) ON CONFLICT DO NOTHING;
INSERT INTO dashboard_slices (dashboard_id, slice_id) VALUES (3, 22) ON CONFLICT DO NOTHING;
INSERT INTO dashboard_slices (dashboard_id, slice_id) VALUES (3, 23) ON CONFLICT DO NOTHING;
INSERT INTO dashboard_slices (dashboard_id, slice_id) VALUES (3, 24) ON CONFLICT DO NOTHING;
INSERT INTO dashboard_slices (dashboard_id, slice_id) VALUES (3, 25) ON CONFLICT DO NOTHING;
INSERT INTO dashboard_slices (dashboard_id, slice_id) VALUES (3, 26) ON CONFLICT DO NOTHING;
COMMIT;